### ISSUE TITLE
新增 博客子版块

### ISSUE THREAD

**Issue by TechQuery** [FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io#8]
基于 [EWAwiki](https://github.com/TechQuery/EasyWiki/tree/EWAwiki) 实现

**Comment by too** [comment]
博客用 Jekyll 然后直接写 Markdown 怎么样？

**Comment by tellxp** [comment]
hexo😁-------- 原始邮件 --------主题：Re: [FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io] 新增 博客子版块 (#8)发件人：Liu Bo 收件人："FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io" 抄送：博客用 Jekyll 然后直接写 Markdown 怎么样？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io","title":"FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@too in #8: 博客用 Jekyll 然后直接写 Markdown 怎么样？"}],"action":{"name":"View Issue","url":"https://github.com/FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io/issues/8#issuecomment-246175680"}}}

**Comment by TechQuery** [comment]
@too @tellxp 

EWAwiki 是 **纯 Web 前端技术**构建的文档系统，不需要 Web 后端、本地命令行预编译，而且没有 HTML 之外的新语法，也完全基于 jQuery，对前端新人更易学易用~

**Comment by tellxp** [comment]
我是说博客试用hexo，jekyll装ruby太麻烦了，而且老是被block

**Comment by TechQuery** [comment]
@tellxp 我是说“博客用 EWAwiki”来搭建……

**Comment by TechQuery** [comment]
已重构为**博客系统**，在 [`hexo` 分支](https://github.com/FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io/tree/hexo)
